# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html
- name: Add users
  user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    uid: "{{ item.uid }}"
    password: "{{ item.password }}"
    group: "{{ item.group }}"
    groups: "{{ item.groups }}"
    shell: "{{ item.shell }}"
    # generate_ssh_key: "{{ item.generate_ssh_key }}"
    # add the user to the groups specified in groups
    # append: true
    state: present
  with_items: "{{ users_def }}"

- name: Sudo without password for wheel group
  copy:
    content: "%{{ item.name }} ALL=(ALL:ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/{{ item.name }}"
    mode: 0440
  with_items: "{{ users_def }}"
