---
# Configure terminal
- name: Install ZSH
  apt:
    name: zsh
    state: present
    update_cache: yes

- name: Install Oh-My-Zsh
  shell: |
    wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    install.sh
    rm install.sh

- name: Install Oh-My-Zsh
  shell: |
    git clone https://github.com/bhilburn/powerlevel9k.git ~/.oh-my-zsh/custom/themes/powerlevel9k
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
    git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
    git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-completions
  ignore_errors: yes
# - name: Install Oh-My-Zsh Nerd Fonts
#   shell: |
#       wget https://github.com/source-foundry/Hack/releases/download/v3.003/Hack-v3.003-ttf.zip
#       unzip Hack-v3.003-ttf.zip
#       cp ttf/* /usr/share/fonts/
#       cp ttf/* /usr/local/share/fonts/
#       fc-cache -f -v
#       rm Hack-v3.003-ttf.zip
