# Playbook for installing Desktop GUI on all hosts
# File name: install-desktop.yml
---
- name: Install Desktop GUI on all hosts if deskop is defined
  hosts: all # Change this setting to you hosts or group specified in /etc/ansible/hosts
  become: true
  # remote_user: root
  # Thi variables file is used
  vars_files:
    - ../vars.yml

  tasks:
    - name: Install tasksel
      apt:
        name:
          - tasksel
        state: present
      when: vm.packages.desktop is defined

    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html
    - name: List all available desktops
      command: tasksel --list-tasks
      when: vm.packages.desktop is defined

      #register: desktops
      # u kubuntu-live	Kubuntu live CD
      # u lubuntu-live	Lubuntu live CD
      # u ubuntu-budgie-live	Ubuntu Budgie live CD
      # u ubuntu-live	Ubuntu live CD
      # u ubuntu-mate-live	Ubuntu MATE Live CD
      # u ubuntustudio-dvd-live	Ubuntu Studio live DVD
      # u xubuntu-live	Xubuntu live CD
      # u cloud-image	Ubuntu Cloud Image (instance)
      # u dns-server	DNS server
      # u kubuntu-desktop	Kubuntu desktop
      # u lamp-server	LAMP server
      # u lubuntu-desktop	Lubuntu Desktop
      # u mail-server	Mail server
      # u postgresql-server	PostgreSQL database
      # u print-server	Print server
      # u samba-server	Samba file server
      # u ubuntu-budgie-desktop	Ubuntu Budgie desktop
      # u ubuntu-desktop	Ubuntu desktop
      # u ubuntu-desktop-default-languages	Ubuntu desktop default languages
      # u ubuntu-desktop-minimal	Ubuntu minimal desktop
      # u ubuntu-desktop-minimal-default-languages	Ubuntu minimal desktop default languages
      # u ubuntu-mate-core	Ubuntu MATE minimal
      # u ubuntu-mate-desktop	Ubuntu MATE desktop
      # u ubuntustudio-audio	Audio recording and editing suite
      # u ubuntustudio-desktop	Ubuntu Studio desktop
      # u ubuntustudio-desktop-core	Ubuntu Studio minimal DE installation
      # u ubuntustudio-fonts	Large selection of font packages
      # u ubuntustudio-graphics	2D/3D creation and editing suite
      # u ubuntustudio-photography	Photograph touchup and editing suite
      # u ubuntustudio-publishing	Publishing applications
      # u ubuntustudio-video	Video creation and editing suite
      # u xubuntu-core	Xubuntu minimal installation
      # u xubuntu-desktop	Xubuntu desktop
      # i openssh-server	OpenSSH server
      # i server	Basic Ubuntu server

      # kubuntu-desktop	Kubuntu desktop ( KDE Desktop )
      # lubuntu-desktop	Lubuntu Desktop ( LXQt desktop )
      # ubuntu-budgie-desktop	Ubuntu Budgie desktop
      # ubuntu-desktop	Ubuntu desktop ( default GNOME )
      # ubuntu-desktop-minimal	Ubuntu minimal desktop ( default GNOME )
      # ubuntu-mate-desktop	Ubuntu MATE desktop
      # ubuntustudio-desktop	Ubuntu Studio desktop ( Xfce-based desktop )
      # ubuntustudio-desktop-core	Ubuntu Studio minimal DE installation ( Xfce-based desktop )
      # xubuntu-desktop	Xubuntu desktop ( Xfce desktop )
    # Install desktop
    - name: Install desktop {{ vm.packages.desktop.name }}
      apt:
        name: "{{ vm.packages.desktop.name }}"
        state: present
      when: vm.packages.desktop is defined

    # # Install Xfce desktop
    # - name: Install Xfce deskop
    #   apt:
    #     name:
    #       - xfce4
    #     state: present
    #   when: vm.packages.desktop is defined

    # Install X2GO
    - name: Install X2Go server & client
      apt:
        name:
          - x2goserver
          - x2goserver-xsession
          - x2goclient
        state: present
      when: vm.packages.desktop is defined

    - shell: "check-language-support -l fr"
      register: languages
      when: vm.packages.desktop is defined

    - debug:
        msg: "{{ languages.stdout }}"
      when: vm.packages.desktop is defined

    # Install language support
    - name: Install language support for desktop
      apt:
        name:
          - language-pack-{{ vm.locale.language.code | lower }}
          - language-pack-gnome-{{ vm.locale.language.code | lower }}
          - language-pack-{{ vm.locale.language.code | lower }}-base
          - language-pack-gnome-{{ vm.locale.language.code | lower }}-base
          - firefox-locale-{{ vm.locale.language.code | lower }}
          - gnome-getting-started-docs-{{ vm.locale.language.code | lower }}
          - gnome-user-docs-{{ vm.locale.language.code | lower }}
          - hunspell-{{ vm.locale.language.code | lower }}
          - hyphen-{{ vm.locale.language.code | lower }}
          - language-pack-{{ vm.locale.language.code | lower }}
          - language-pack-gnome-{{ vm.locale.language.code | lower }}
          - libreoffice-help-{{ vm.locale.language.code | lower }}
          - libreoffice-l10n-{{ vm.locale.language.code | lower }}
          - mythes-{{ vm.locale.language.code | lower }}
          - thunderbird-locale-{{ vm.locale.language.code | lower }}
          - w{{ vm.locale.language.name }}
        state: present
        update_cache: yes
      when: vm.packages.desktop is defined
