# Playbook for installing kubernetes on all hosts
# File name: install-kubernetes.yml
---
- name: Install Kubernetes on all hosts
  hosts: all
  become: yes

  # Thi variables file is used
  vars_files:
    - ../vars.yml

  tasks:

    # Installing kubelet, kubeadm and kubectl
    - name: Add an apt signing key for Kubernetes
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Adding apt repository for Kubernetes
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes.list

    - name: Install Kubernetes binaries
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - kubelet={{ vm.packages.kubernetes.version }}
          - kubeadm={{ vm.packages.kubernetes.version }}
          - kubectl={{ vm.packages.kubernetes.version }}
          - kubernetes-cni
      ignore_errors: yes

    - name: Check Kubernetes version
      command: kubeadm version -o 'json'
      register: kube_version

    - debug:
        msg: "{{ kube_version.stdout }}"

    # Kubelet will not start if the system has swap enabled,
    # so we are disabling swap
    - name: Remove swapfile from /etc/fstab
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none

    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    # @see https://github.com/kubernetes/release/pull/672
    # - name: Configure node ip
    #   lineinfile:
    #     path: /etc/default/kubelet
    #     line: KUBELET_EXTRA_ARGS=--node-ip={{ ansible_hostname }}

    # Restart kubelet
    - name: Restart kubelet
      service:
        name: kubelet
        daemon_reload: yes
        state: restarted

    # Pull all images for offline install
    - name: Pull all images for offline install
      command: kubeadm config images pull