all:
  hosts:
    10.0.0.25:
      ansible_ssh_user: ntran
      ansible_ssh_pass: superlinux
      ansible_sudo_pass: superlinux
  vars:
    ansible_connection: ssh
    ansible_ssh_port: 22
    ansible_python_interpreter: /usr/bin/python3
