---
- hosts: all
  roles:
    - common
  tags:
    - common

- hosts: all
  roles:
    - powerline
    - oh-my-zsh
  tags:
    - terminal

- hosts: all
  roles:
    - role: docker
      vars:
        version: 20.10.14
        containerd: 1.5.11
        init_swarm: true
  tags:
    - docker

- hosts: all
  roles:
    - role: java
      vars:
        version: 8
  tags:
    - java

- hosts: all
  roles:
    - role: maven
      vars:
        version: 3.6.3
  tags:
    - maven

- hosts: all
  roles:
    - role: nodejs
      vars:
        version: 15.x
  tags:
    - nodejs

- hosts: all
  roles:
    - role: desktop
      vars:
        desktop: ubuntu-desktop
    - role: virtualbox-guest
  tags:
    - desktop

- hosts: all
  roles:
    - locales
  tags:
    - locales

- hosts: all
  roles:
    - keyboard
  tags:
    - keyboard

- hosts: all
  roles:
    - role: users
      vars:
        users_def:
          - name: ntran
            comment: Nhi TRAN
            uid: 1101
            password: $6$sk.NgiIbn9Mh1FC9$i5Epdv819Qg/Ttx40XwHvhetoPlN9z3sMe/sRBgQ7gdG32Kghu.KqTE8uYro4fbu38XwKB7Mtc1F3IYBra23Q/
            # primary group
            group: tran
            groups: docker,devops
            shell: /bin/bash
            # generate_ssh_key: true
        groups_def:
          - name: tran
            gid: 1100
          - name: devops
            gid: 1200
  tags:
    - users
